name: Get Latest Docker Tag

on:
  push:
    branches:
      - main

jobs:
  get-latest-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get latest Docker tag
      run: |
        TAGS_URL="https://registry.hub.docker.com/v2/namespaces/yexundao/repositories/wakeup_pc/tags?page=2&page_size=1"
        TAGS_RESPONSE=$(curl -s $TAGS_URL)
        LATEST_TAG=$(echo $TAGS_RESPONSE | jq -r '.results[] | .name' | sort -V | tail -n1 | awk -F'-' '{print $1}')
        echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

    - name: Increment version
      run: |
        # 读取最新版本号并分割为数组
        IFS='.' read -r major minor patch <<< $LATEST_TAG
        echo $major
        echo $minor
        echo $patch
        # 递增补丁版本号
        patch=$((patch + 1))
        # 如果补丁版本号达到10，重置为0并递增次版本号
        if [ $patch -eq 10 ]; then
            patch=0
            minor=$((minor + 1))
            # 如果次版本号达到10，重置为0并递增主版本号
            if [ $minor -eq 10 ]; then
                minor=0
                major=$((major + 1))
            fi
        fi
        # 构造新版本号
        echo $major
        echo $minor
        echo $patch
        NEW_VERSION="$major.$minor.$patch"
        echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

    - name: Show new version
      run: echo $NEW_VERSION