name: Get Latest Docker Tag

on:
  push:
    branches:
      - main

jobs:
  get-latest-tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get latest Docker tag
      run: |
        TAGS_URL="https://registry.hub.docker.com/v2/namespaces/yexundao/repositories/wakeup_pc/tags?page=2&page_size=1"
        TAGS_RESPONSE=$(curl -s $TAGS_URL)
        echo "TAGS_RESPONSE=$TAGS_RESPONSE" >> $GITHUB_ENV

    - name: Show latest tag
      run: echo $TAGS_RESPONSE | jq -r '.results[] | .name' | sort -V | tail -n1 | awk -F'-' '{print $1}'

