name: Publish Docker Image by Self-Hosted Runner

on:
  # push:
  #   tags:
  #     - "v*"
  # 手动CI构建按钮增加
  workflow_dispatch:
    inputs:
      version:
        description: '输入版本号，格式为X.Y.Z'
        required: true
        default: ''
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    # 分为两个jobs，amd64走在线ubuntu-latest运行器，arm64走自托管运行器
    strategy:
      matrix:
        platform: [amd64, arm64]
        include:
          - platform: amd64
            runner: ubuntu-latest
          - platform: arm64
            runner: armbian
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Check runner
        id: check_runner
        run: echo "runner=${{ matrix.runner }}" >> $GITHUB_OUTPUT

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Use tags or version
        id: final_tags
        run: |
          if [ -z "${{ github.event.inputs.version }}" ]; then
            tags=${{ steps.get_version.outputs.VERSION }}
          else
            tags=${{ github.event.inputs.version }}
          fi

          if [ "${{ steps.check_runner.outputs.runner }}" == "armbian" ]; then
            echo "tags=$tags-arm" >> $GITHUB_OUTPUT
            echo "latest_tags=latest-arm" >> $GITHUB_OUTPUT
          else
            echo "tags=$tags" >> $GITHUB_OUTPUT
            echo "latest_tags=latest" >> $GITHUB_OUTPUT
          fi

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: yexundao/wakeup_pc
          tags: |
                type=raw,value=${{ steps.final_tags.outputs.tags }}
                type=raw,value=${{ steps.final_tags.outputs.latest_tags }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./docker
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
